// <auto-generated />
namespace CenitoIoT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update01));
        
        string IMigrationMetadata.Id
        {
            get { return "201607031927187_update01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
